name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    - name: Download dependencies
      run: |
        dependency_count=$(go list -m all | wc -l)
        are_dependencies_present=$([ "$dependency_count" -gt 1 ] && echo true || echo false)

        if [ "$are_dependencies_present" = true ]; then
          go mod download
        fi

    - name: Run make test
      run: make test
